services:
  emqx:
    image: emqx/emqx:5.7.2
    container_name: emqx_windfarm
    restart: unless-stopped
    ports:
      - "1883:1883"     # MQTT (sin TLS)
      - "8883:8883"     # MQTT (TLS)
      - "8083:8083"     # MQTT sobre WebSocket (sin TLS)
      - "8084:8084"     # MQTT sobre WebSocket (TLS)
      - "18083:18083"   # Dashboard web

  api:
    build: 
      context: ./AlertHistoryBackend   # carpeta base del proyecto Flask
      dockerfile: Dockerfile
    container_name: flask_api_dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development